language: none

build:
  ci:
    - echo $AWSKEYS_INTEGRATION_ACCESSKEY
    - echo $AWSKEYS_INTEGRATION_SECRETKEY
    - aws configure aws_access_key_id $AWSKEYS_INTEGRATION_ACCESSKEY
    - aws configure aws_secret_access_key $AWSKEYS_INTEGRATION_SECRETKEY
    - aws s3 cp shippable.yml s3://shippabletest/test.txt

resources:
  - name:           awskeys
    type:           integration
    integration:    awskeys
    
jobs:
  - name: awskeys-cli-sample_runCI
    type: runCI
    steps:
      - IN: awskeys 
    

