language: none

build:
  ci:
    - aws configure set region us-east-1 --profile default
    - aws configure set aws_access_key_id $AWSKEYS_INTEGRATION_ACCESSKEY --profile default
    - aws configure set aws_secret_access_key $AWSKEYS_INTEGRATION_SECRETKEY --profile default
    - aws s3 cp shippable.yml s3://shippabletest/test.txt

resources:
  - name:           awskeys
    type:           integration
    integration:    awskeys
    
jobs:
  - name: awskeys-cli-sample_runCI
    type: runCI
    steps:
      - IN: awskeys 
    

