language: none

build:
  ci:
    - echo $AWS_ACCESS_KEY_ID 
    - echo $AWS_SECRET_ACCESS_KEY
    - aws s3 cp shippable.yml s3://shippabletest/test.txt

resources:
  - name:           awskeys
    type:           integration
    integration:    awskeys
    
jobs:
  - name: ci-nodejs_runCI
    type: runCI
    steps:
      -IN : awskeys 
    

